apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeployment
spec:
   replicas: 1
   selector:     #tells the controller which pod to watch/belong to
    matchLabels:
        name: deployment
   template:
         metadata:
           name: testpod
           labels:
              name: deployment
         spec:
            containers:
            - name: c00
              image: httpd
              ports:
               - containerPort : 80
