apiVersion: v1
kind: Pod
metadata:
   name: myenvconfig
spec:
 containers: 
 - name: c1
   image: nginx
   env:
   - name: MYENV            # env name in which value of the key is stored
     valueFrom:
        configMapKeyRef:
           name: mymap       # name of the config created
           key: sample.conf      
