apiVersion: v1
kind: Pod
metadata:
   name: myvolsecret
spec:
 containers:
 - name: c1
   image: nginx
   volumeMounts:
     - name: testsecret
       mountPath: "/tmp/mysecrets" # the secret file will be mounted as Readonly by default here
 volumes:
 - name: testsecret
   secret:
     secretName: mysecret 
