apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
 replicas: 2
 selector:
   app: dev
 template:
   metadata:
     name: webpod
     labels:
       app: dev
   spec:
     containers:
     - name: nginx
       image: nginx
